### ISSUE TITLE
<maj><tab> ?

### ISSUE THREAD

**Issue by ckp95** [dbaty/testfinder#2]
>The demo above is me typing pytest followed by <Maj>-<Tab> (which is my configured key for "advanced" auto-completion) and then typing characters of the test function I am looking for.

I know this isn't really the focus of the repo, but how do you configure this key combination? I find zsh's completion API hard to understand so I'd be grateful if you could give me a pointer here.

**Comment by dbaty** [comment]
I wrote `<Maj>-<Tab>` in the README, but it was a mistake. That's French for `<Shift>-<Tab>`, which I configure like this in `.zshrc`:

    bindkey '^[[Z' fzf-completion

I [fixed the explanation](https://github.com/dbaty/testfinder/commit/f2005d462b2304f878ce9879d0d19c05c23c0e5c) in the README for clarity.
